name: Docker ECR & ASG CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 저장소 소스코드 체크아웃
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      # Step 2: AWS 자격 증명 구성
      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload docker-compose to S3
        run: |
          aws s3 cp ./docker-compose.yaml s3://std04-state-bucket-2026/docker-compose.yaml

      # Step 3: Amazon ECR 프라이빗 레지스트리 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Docker 이미지 빌드 및 ECR 푸시
      - name: Build and push Docker image to ECR
        # env:
        #   # ECR 로그인 액션의 출력에서 레지스트리 URI를 자동으로 가져옴 (예: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com)
        #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #   # 본인의 ECR 리포지토리 이름 (예: ex4-nginx 또는 본인이 생성한 ECR 이름)
        #   ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        #   IMAGE_TAG: ${{github.sha}}
        run: |
          # 1. 커밋 해시 태그 및 latest 태그로 빌드 (루트 경로 '.' 기준)
          docker build -t 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:nginx1.31.3-ecr ./nginx
          docker build -t 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest ./nginx

          # 2. ECR로 두 태그 모두 푸시
          docker push 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:nginx1.31.3-ecr
          docker push 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com/std04/nginx:latest
      - name: 프라이빗 인스턴스 컨테이너 배포
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Cicd,Values=asg" \
            --comment "Deploy custom Docker image from ECR" \
            --parameters 'commands=[
              "systemctl stop nginx || true",
              "mkdir -p /home/ec2-user/app",
              "cd /home/ec2-user/app",
              "aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 925047940866.dkr.ecr.ap-northeast-2.amazonaws.com",
              "aws s3 cp s3://std04-state-bucket-2026/docker-compose.yaml ./docker-compose.yaml",
              "docker compose pull",
              "docker compose up -d --remove-orphans",
              "docker image prune -f"
            ]' \
            --region ap-northeast-2